Name:           ros-hydro-nao-moveit-config
Version:        0.0.4
Release:        0%{?dist}
Summary:        ROS nao_moveit_config package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-joint-state-publisher
Requires:       ros-hydro-moveit-fake-controller-manager
Requires:       ros-hydro-moveit-planners-ompl
Requires:       ros-hydro-moveit-ros-move-group
Requires:       ros-hydro-moveit-ros-visualization
Requires:       ros-hydro-moveit-simple-controller-manager
Requires:       ros-hydro-nao-description
Requires:       ros-hydro-robot-state-publisher
Requires:       ros-hydro-xacro
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-nao-description

%description
An automatically generated package with all the configuration and launch files
for using the NAO robot with the MoveIt Motion Planning Framework

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Thu Dec 04 2014 Mikael Arguedas <mikael.arguedas@gmail.com> - 0.0.4-0
- Autogenerated by Bloom

* Thu Sep 18 2014 Mikael Arguedas <assistant@moveit.ros.org> - 0.0.1-0
- Autogenerated by Bloom

